//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColeHop.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColeHop.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizaciones activas.
        /// </summary>
        public static string ActiveAuthorizations {
            get {
                return ResourceManager.GetString("ActiveAuthorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Persona Autorizada.
        /// </summary>
        public static string AddAuthorizedPerson {
            get {
                return ResourceManager.GetString("AddAuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Hijo.
        /// </summary>
        public static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ✓ Ya recogido.
        /// </summary>
        public static string AlreadyPickedUp {
            get {
                return ResourceManager.GetString("AlreadyPickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColeHop.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerque el DNI electrónico al lector....
        /// </summary>
        public static string ApproachDniToReader {
            get {
                return ResourceManager.GetString("ApproachDniToReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión de la aplicación.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario de autorizaciones.
        /// </summary>
        public static string AuthorizationCalendar {
            get {
                return ResourceManager.GetString("AuthorizationCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización creada exitosamente.
        /// </summary>
        public static string AuthorizationCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AuthorizationCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de autorización.
        /// </summary>
        public static string AuthorizationDetail {
            get {
                return ResourceManager.GetString("AuthorizationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización no encontrada.
        /// </summary>
        public static string AuthorizationNotFound {
            get {
                return ResourceManager.GetString("AuthorizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización actualizada correctamente.
        /// </summary>
        public static string AuthorizationUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AuthorizationUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niños autorizados.
        /// </summary>
        public static string AuthorizedChildren {
            get {
                return ResourceManager.GetString("AuthorizedChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada.
        /// </summary>
        public static string AuthorizedPerson {
            get {
                return ResourceManager.GetString("AuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas Autorizadas.
        /// </summary>
        public static string AuthorizedPersons {
            get {
                return ResourceManager.GetString("AuthorizedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas autorizadas.
        /// </summary>
        public static string AuthorizedPersonsMenu {
            get {
                return ResourceManager.GetString("AuthorizedPersonsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerque el DNI electrónico.
        /// </summary>
        public static string BringDnieClose {
            get {
                return ResourceManager.GetString("BringDnieClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CAN debe tener 6 dígitos.
        /// </summary>
        public static string CanMustBe6Digits {
            get {
                return ResourceManager.GetString("CanMustBe6Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este niño ya ha sido recogido hoy.
        /// </summary>
        public static string ChildAlreadyPickedUp {
            get {
                return ResourceManager.GetString("ChildAlreadyPickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo eliminado correctamente.
        /// </summary>
        public static string ChildDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ChildDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del Hijo.
        /// </summary>
        public static string ChildDetail {
            get {
                return ResourceManager.GetString("ChildDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado el niño a recoger.
        /// </summary>
        public static string ChildNotSpecified {
            get {
                return ResourceManager.GetString("ChildNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijos.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo actualizado correctamente.
        /// </summary>
        public static string ChildUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ChildUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea eliminar esta autorización?.
        /// </summary>
        public static string ConfirmDeleteAuthorization {
            get {
                return ResourceManager.GetString("ConfirmDeleteAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar a {0}?.
        /// </summary>
        public static string ConfirmDeleteChild {
            get {
                return ResourceManager.GetString("ConfirmDeleteChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar a {0} {1}?.
        /// </summary>
        public static string ConfirmDeletePerson {
            get {
                return ResourceManager.GetString("ConfirmDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar eliminación.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron cargar las recogidas: {0}.
        /// </summary>
        public static string CouldNotLoadPickups {
            get {
                return ResourceManager.GetString("CouldNotLoadPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El curso es obligatorio.
        /// </summary>
        public static string CourseRequired {
            get {
                return ResourceManager.GetString("CourseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear autorización.
        /// </summary>
        public static string CreateAuthorization {
            get {
                return ResourceManager.GetString("CreateAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta nueva.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de recogidas del día.
        /// </summary>
        public static string DailyPickupList {
            get {
                return ResourceManager.GetString("DailyPickupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscuro.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola! ¿Qué necesitas?.
        /// </summary>
        public static string DashboardGreeting {
            get {
                return ResourceManager.GetString("DashboardGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dddd, d &apos;de&apos; MMMM &apos;de&apos; yyyy.
        /// </summary>
        public static string DateFormatLong {
            get {
                return ResourceManager.GetString("DateFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar autorización.
        /// </summary>
        public static string DeleteAuthorization {
            get {
                return ResourceManager.GetString("DeleteAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollador.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI no tiene un formato válido.
        /// </summary>
        public static string DniInvalidFormat {
            get {
                return ResourceManager.GetString("DniInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se detectó el DNI en 10 segundos. Por favor, intente de nuevo..
        /// </summary>
        public static string DniNotDetectedTimeout {
            get {
                return ResourceManager.GetString("DniNotDetectedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI es obligatorio.
        /// </summary>
        public static string DniRequired {
            get {
                return ResourceManager.GetString("DniRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Educativa.
        /// </summary>
        public static string EducationInfo {
            get {
                return ResourceManager.GetString("EducationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de enseñanza.
        /// </summary>
        public static string EducationType {
            get {
                return ResourceManager.GetString("EducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de enseñanza es obligatorio.
        /// </summary>
        public static string EducationTypeRequired {
            get {
                return ResourceManager.GetString("EducationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email es obligatorio.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, active NFC en los ajustes.
        /// </summary>
        public static string EnableNfcInSettings {
            get {
                return ResourceManager.GetString("EnableNfcInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar notificaciones.
        /// </summary>
        public static string EnableNotifications {
            get {
                return ResourceManager.GetString("EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de fin debe ser posterior a la fecha de inicio.
        /// </summary>
        public static string EndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el CAN del DNI (6 dígitos).
        /// </summary>
        public static string EnterCanPrompt {
            get {
                return ResourceManager.GetString("EnterCanPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el motivo del rechazo.
        /// </summary>
        public static string EnterRejectionReason {
            get {
                return ResourceManager.GetString("EnterRejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código CAN introducido no es correcto. Revise los 6 dígitos que aparecen en la parte inferior derecha del anverso de su DNI..
        /// </summary>
        public static string ErrorCanIncorrect {
            get {
                return ResourceManager.GetString("ErrorCanIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear autorización: {0}.
        /// </summary>
        public static string ErrorCreatingAuthorization {
            get {
                return ResourceManager.GetString("ErrorCreatingAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al verificar la seguridad del documento. El CAN podría ser incorrecto o el DNI se movió durante la lectura. Inténtelo de nuevo..
        /// </summary>
        public static string ErrorCrypto {
            get {
                return ResourceManager.GetString("ErrorCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar: {0}.
        /// </summary>
        public static string ErrorDeleting {
            get {
                return ResourceManager.GetString("ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido acceder a los datos del DNI. Asegúrese de que el documento es un DNI electrónico válido..
        /// </summary>
        public static string ErrorDniAccess {
            get {
                return ResourceManager.GetString("ErrorDniAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error de comunicación con el DNI. Vuelva a acercar el documento y manténgalo quieto durante la lectura..
        /// </summary>
        public static string ErrorDniCommunication {
            get {
                return ResourceManager.GetString("ErrorDniCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al leer el DNI. Compruebe que el CAN es correcto, mantenga el documento quieto sobre el teléfono e inténtelo de nuevo..
        /// </summary>
        public static string ErrorDniFallback {
            get {
                return ResourceManager.GetString("ErrorDniFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicación con el DNI electrónico. Mantenga el documento pegado al teléfono sin moverlo e inténtelo de nuevo..
        /// </summary>
        public static string ErrorDniGenericComm {
            get {
                return ResourceManager.GetString("ErrorDniGenericComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar personas autorizadas: {0}.
        /// </summary>
        public static string ErrorLoadingAuthorizedPersons {
            get {
                return ResourceManager.GetString("ErrorLoadingAuthorizedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar hijos: {0}.
        /// </summary>
        public static string ErrorLoadingChildren {
            get {
                return ResourceManager.GetString("ErrorLoadingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar datos: {0}.
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la lectura NFC. Asegúrese de que el DNI está bien posicionado y no lo mueva durante el proceso..
        /// </summary>
        public static string ErrorNfcGeneric {
            get {
                return ResourceManager.GetString("ErrorNfcGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al establecer la conexión segura con el DNI. Verifique que el CAN es correcto y vuelva a intentarlo..
        /// </summary>
        public static string ErrorPaceConnection {
            get {
                return ResourceManager.GetString("ErrorPaceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar: {0}.
        /// </summary>
        public static string ErrorRegistering {
            get {
                return ResourceManager.GetString("ErrorRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar: {0}.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar cambios: {0}.
        /// </summary>
        public static string ErrorSavingChanges {
            get {
                return ResourceManager.GetString("ErrorSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación segura con el DNI se ha interrumpido. Vuelva a acercar el documento e inténtelo de nuevo..
        /// </summary>
        public static string ErrorSecureMessaging {
            get {
                return ResourceManager.GetString("ErrorSecureMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar recogida.
        /// </summary>
        public static string ErrorStartingPickup {
            get {
                return ResourceManager.GetString("ErrorStartingPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha perdido la conexión con el DNI. Mantenga el documento pegado al teléfono sin moverlo durante toda la lectura..
        /// </summary>
        public static string ErrorTagLost {
            get {
                return ResourceManager.GetString("ErrorTagLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicación NFC. Asegúrese de que el DNI está bien posicionado sobre el lector NFC del teléfono..
        /// </summary>
        public static string ErrorTransceive {
            get {
                return ResourceManager.GetString("ErrorTransceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde: .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El grupo es obligatorio.
        /// </summary>
        public static string GroupRequired {
            get {
                return ResourceManager.GetString("GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identidad verificada: {0}.
        /// </summary>
        public static string IdentityVerified {
            get {
                return ResourceManager.GetString("IdentityVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contexto de recogida no válido.
        /// </summary>
        public static string InvalidPickupContext {
            get {
                return ResourceManager.GetString("InvalidPickupContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma cambiado. Se reiniciará la aplicación para aplicar los cambios..
        /// </summary>
        public static string LanguageChangedRestart {
            get {
                return ResourceManager.GetString("LanguageChangedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos son obligatorios.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claro.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como Profesor.
        /// </summary>
        public static string LoginAsTeacher {
            get {
                return ResourceManager.GetString("LoginAsTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como Tutor.
        /// </summary>
        public static string LoginAsTutor {
            get {
                return ResourceManager.GetString("LoginAsTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menores.
        /// </summary>
        public static string Minors {
            get {
                return ResourceManager.GetString("Minors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis hijos.
        /// </summary>
        public static string MyChildren {
            get {
                return ResourceManager.GetString("MyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NFC desactivado. Actívelo para continuar..
        /// </summary>
        public static string NfcDisabledWarning {
            get {
                return ResourceManager.GetString("NfcDisabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI detectado. Mantenga el DNI en el lector hasta que se complete la comprobación..
        /// </summary>
        public static string NfcDniDetectedKeepStill {
            get {
                return ResourceManager.GetString("NfcDniDetectedKeepStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estableciendo canal seguro (PACE)....
        /// </summary>
        public static string NfcEstablishingSecureChannel {
            get {
                return ResourceManager.GetString("NfcEstablishingSecureChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenga el DNI en el lector
        ///hasta que se complete la comprobación.
        /// </summary>
        public static string NfcKeepDniOnReader {
            get {
                return ResourceManager.GetString("NfcKeepDniOnReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NFC no soportado.
        /// </summary>
        public static string NfcNotSupported {
            get {
                return ResourceManager.GetString("NfcNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este dispositivo no soporta NFC.
        /// </summary>
        public static string NfcNotSupportedDevice {
            get {
                return ResourceManager.GetString("NfcNotSupportedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coloque la parte trasera del DNIe
        ///sobre la parte superior del teléfono.
        /// </summary>
        public static string NfcPositionInstructions {
            get {
                return ResourceManager.GetString("NfcPositionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leyendo datos del DNIe....
        /// </summary>
        public static string NfcReadingDnieData {
            get {
                return ResourceManager.GetString("NfcReadingDnieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal seguro activo. Preparando lectura....
        /// </summary>
        public static string NfcSecureChannelReading {
            get {
                return ResourceManager.GetString("NfcSecureChannelReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay autorizaciones activas.
        /// </summary>
        public static string NoActiveAuthorizations {
            get {
                return ResourceManager.GetString("NoActiveAuthorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay contexto de recogida activo.
        /// </summary>
        public static string NoActivePickupContext {
            get {
                return ResourceManager.GetString("NoActivePickupContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay personas autorizadas.
        /// </summary>
        public static string NoAuthorizedPersons {
            get {
                return ResourceManager.GetString("NoAuthorizedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no se ha recogido ningún niño.
        /// </summary>
        public static string NoChildrenPickedUpYet {
            get {
                return ResourceManager.GetString("NoChildrenPickedUpYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay hijos registrados.
        /// </summary>
        public static string NoChildrenRegistered {
            get {
                return ResourceManager.GetString("NoChildrenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay altas pendientes.
        /// </summary>
        public static string NoPendingApprovals {
            get {
                return ResourceManager.GetString("NoPendingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay recogidas pendientes.
        /// </summary>
        public static string NoPendingPickups {
            get {
                return ResourceManager.GetString("NoPendingPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No autorizado.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Mes.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Semana.
        /// </summary>
        public static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente de aprobación.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altas pendientes.
        /// </summary>
        public static string PendingApprovals {
            get {
                return ResourceManager.GetString("PendingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente de recogida.
        /// </summary>
        public static string PendingPickup {
            get {
                return ResourceManager.GetString("PendingPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes de recoger.
        /// </summary>
        public static string PendingPickups {
            get {
                return ResourceManager.GetString("PendingPickups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} puede recoger a {1}.
        /// </summary>
        public static string PersonCanPickupChild {
            get {
                return ResourceManager.GetString("PersonCanPickupChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} con DNI {2} puede recoger a {3}.
        /// </summary>
        public static string PersonCanPickupChildWithDni {
            get {
                return ResourceManager.GetString("PersonCanPickupChildWithDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada eliminada correctamente.
        /// </summary>
        public static string PersonDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PersonDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Persona Autorizada.
        /// </summary>
        public static string PersonDetail {
            get {
                return ResourceManager.GetString("PersonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} no tiene autorización vigente para recoger a este menor..
        /// </summary>
        public static string PersonNotAuthorizedForChild {
            get {
                return ResourceManager.GetString("PersonNotAuthorizedForChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada actualizada correctamente.
        /// </summary>
        public static string PersonUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PersonUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogidos.
        /// </summary>
        public static string PickedUp {
            get {
                return ResourceManager.GetString("PickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogido por:.
        /// </summary>
        public static string PickedUpBy {
            get {
                return ResourceManager.GetString("PickedUpBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recoge:.
        /// </summary>
        public static string PicksUp {
            get {
                return ResourceManager.GetString("PicksUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogida autorizada.
        /// </summary>
        public static string PickupAuthorized {
            get {
                return ResourceManager.GetString("PickupAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogida confirmada correctamente.
        /// </summary>
        public static string PickupConfirmedSuccess {
            get {
                return ResourceManager.GetString("PickupConfirmedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogida no autorizada.
        /// </summary>
        public static string PickupNotAuthorized {
            get {
                return ResourceManager.GetString("PickupNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recogida de {0}.
        /// </summary>
        public static string PickupOf {
            get {
                return ResourceManager.GetString("PickupOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infantil.
        /// </summary>
        public static string Preschool {
            get {
                return ResourceManager.GetString("Preschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulse el botón + para crear una nueva autorización.
        /// </summary>
        public static string PressButtonToAddAuthorization {
            get {
                return ResourceManager.GetString("PressButtonToAddAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulsa el botón + para añadir uno.
        /// </summary>
        public static string PressButtonToAddOne {
            get {
                return ResourceManager.GetString("PressButtonToAddOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primaria.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo para escanear DNI para recoger a {0}.
        /// </summary>
        public static string ReadyToScanForChild {
            get {
                return ResourceManager.GetString("ReadyToScanForChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo....
        /// </summary>
        public static string ReasonPlaceholder {
            get {
                return ResourceManager.GetString("ReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completado exitosamente.
        /// </summary>
        public static string RegistrationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("RegistrationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar alta.
        /// </summary>
        public static string RejectChild {
            get {
                return ResourceManager.GetString("RejectChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud rechazada.
        /// </summary>
        public static string RejectedRegistration {
            get {
                return ResourceManager.GetString("RejectedRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La relación es obligatoria.
        /// </summary>
        public static string RelationshipRequired {
            get {
                return ResourceManager.GetString("RelationshipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escaneo cancelado.
        /// </summary>
        public static string ScanCancelled {
            get {
                return ResourceManager.GetString("ScanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escuela.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La escuela es obligatoria.
        /// </summary>
        public static string SchoolRequired {
            get {
                return ResourceManager.GetString("SchoolRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona al menos un hijo.
        /// </summary>
        public static string SelectAtLeastOneChild {
            get {
                return ResourceManager.GetString("SelectAtLeastOneChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar al menos un hijo.
        /// </summary>
        public static string SelectAtLeastOneChildMessage {
            get {
                return ResourceManager.GetString("SelectAtLeastOneChildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una persona autorizada.
        /// </summary>
        public static string SelectAuthorizedPerson {
            get {
                return ResourceManager.GetString("SelectAuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona los hijos.
        /// </summary>
        public static string SelectChildren {
            get {
                return ResourceManager.GetString("SelectChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} seleccionado(s).
        /// </summary>
        public static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona persona autorizada.
        /// </summary>
        public static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione tipo.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Define el período.
        /// </summary>
        public static string SetDates {
            get {
                return ResourceManager.GetString("SetDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar escaneo.
        /// </summary>
        public static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel del Profesor.
        /// </summary>
        public static string TeacherDashboard {
            get {
                return ResourceManager.GetString("TeacherDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo agotado.
        /// </summary>
        public static string TimeoutExpired {
            get {
                return ResourceManager.GetString("TimeoutExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera agotado. Intente de nuevo..
        /// </summary>
        public static string TimeoutRetry {
            get {
                return ResourceManager.GetString("TimeoutRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta: .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demasiados intentos. Espere {0}s....
        /// </summary>
        public static string TooManyAttemptsWait {
            get {
                return ResourceManager.GetString("TooManyAttemptsWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel del Tutor.
        /// </summary>
        public static string TutorDashboard {
            get {
                return ResourceManager.GetString("TutorDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso no autorizado.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado desconocido.
        /// </summary>
        public static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o email.
        /// </summary>
        public static string UsernameOrEmail {
            get {
                return ResourceManager.GetString("UsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo de validez.
        /// </summary>
        public static string ValidityPeriod {
            get {
                return ResourceManager.GetString("ValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de verificación.
        /// </summary>
        public static string VerificationError {
            get {
                return ResourceManager.GetString("VerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión: .
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando DNI electrónico....
        /// </summary>
        public static string WaitingForDni {
            get {
                return ResourceManager.GetString("WaitingForDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
