//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColeHop.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColeHop.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Persona Autorizada.
        /// </summary>
        public static string AddAuthorizedPerson {
            get {
                return ResourceManager.GetString("AddAuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Hijo.
        /// </summary>
        public static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColeHop.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión de la aplicación.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización creada exitosamente.
        /// </summary>
        public static string AuthorizationCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AuthorizationCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niños autorizados.
        /// </summary>
        public static string AuthorizedChildren {
            get {
                return ResourceManager.GetString("AuthorizedChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada.
        /// </summary>
        public static string AuthorizedPerson {
            get {
                return ResourceManager.GetString("AuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas Autorizadas.
        /// </summary>
        public static string AuthorizedPersons {
            get {
                return ResourceManager.GetString("AuthorizedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo eliminado correctamente.
        /// </summary>
        public static string ChildDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ChildDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del Hijo.
        /// </summary>
        public static string ChildDetail {
            get {
                return ResourceManager.GetString("ChildDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijos.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo actualizado correctamente.
        /// </summary>
        public static string ChildUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ChildUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar a {0}?.
        /// </summary>
        public static string ConfirmDeleteChild {
            get {
                return ResourceManager.GetString("ConfirmDeleteChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar a {0} {1}?.
        /// </summary>
        public static string ConfirmDeletePerson {
            get {
                return ResourceManager.GetString("ConfirmDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar eliminación.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El curso es obligatorio.
        /// </summary>
        public static string CourseRequired {
            get {
                return ResourceManager.GetString("CourseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear autorización.
        /// </summary>
        public static string CreateAuthorization {
            get {
                return ResourceManager.GetString("CreateAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscuro.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollador.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI no tiene un formato válido.
        /// </summary>
        public static string DniInvalidFormat {
            get {
                return ResourceManager.GetString("DniInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI es obligatorio.
        /// </summary>
        public static string DniRequired {
            get {
                return ResourceManager.GetString("DniRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Educativa.
        /// </summary>
        public static string EducationInfo {
            get {
                return ResourceManager.GetString("EducationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de enseñanza.
        /// </summary>
        public static string EducationType {
            get {
                return ResourceManager.GetString("EducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de enseñanza es obligatorio.
        /// </summary>
        public static string EducationTypeRequired {
            get {
                return ResourceManager.GetString("EducationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email es obligatorio.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar notificaciones.
        /// </summary>
        public static string EnableNotifications {
            get {
                return ResourceManager.GetString("EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de fin debe ser posterior a la fecha de inicio.
        /// </summary>
        public static string EndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear autorización: {0}.
        /// </summary>
        public static string ErrorCreatingAuthorization {
            get {
                return ResourceManager.GetString("ErrorCreatingAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar: {0}.
        /// </summary>
        public static string ErrorDeleting {
            get {
                return ResourceManager.GetString("ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar datos: {0}.
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar: {0}.
        /// </summary>
        public static string ErrorRegistering {
            get {
                return ResourceManager.GetString("ErrorRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar: {0}.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar cambios: {0}.
        /// </summary>
        public static string ErrorSavingChanges {
            get {
                return ResourceManager.GetString("ErrorSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El grupo es obligatorio.
        /// </summary>
        public static string GroupRequired {
            get {
                return ResourceManager.GetString("GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos son obligatorios.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claro.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay personas autorizadas.
        /// </summary>
        public static string NoAuthorizedPersons {
            get {
                return ResourceManager.GetString("NoAuthorizedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay hijos registrados.
        /// </summary>
        public static string NoChildrenRegistered {
            get {
                return ResourceManager.GetString("NoChildrenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Mes.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Semana.
        /// </summary>
        public static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada eliminada correctamente.
        /// </summary>
        public static string PersonDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PersonDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Persona Autorizada.
        /// </summary>
        public static string PersonDetail {
            get {
                return ResourceManager.GetString("PersonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona autorizada actualizada correctamente.
        /// </summary>
        public static string PersonUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PersonUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infantil.
        /// </summary>
        public static string Preschool {
            get {
                return ResourceManager.GetString("Preschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulsa el botón + para añadir uno.
        /// </summary>
        public static string PressButtonToAddOne {
            get {
                return ResourceManager.GetString("PressButtonToAddOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primaria.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completado exitosamente.
        /// </summary>
        public static string RegistrationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("RegistrationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La relación es obligatoria.
        /// </summary>
        public static string RelationshipRequired {
            get {
                return ResourceManager.GetString("RelationshipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escuela.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La escuela es obligatoria.
        /// </summary>
        public static string SchoolRequired {
            get {
                return ResourceManager.GetString("SchoolRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona al menos un hijo.
        /// </summary>
        public static string SelectAtLeastOneChild {
            get {
                return ResourceManager.GetString("SelectAtLeastOneChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar al menos un hijo.
        /// </summary>
        public static string SelectAtLeastOneChildMessage {
            get {
                return ResourceManager.GetString("SelectAtLeastOneChildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una persona autorizada.
        /// </summary>
        public static string SelectAuthorizedPerson {
            get {
                return ResourceManager.GetString("SelectAuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona los hijos.
        /// </summary>
        public static string SelectChildren {
            get {
                return ResourceManager.GetString("SelectChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} seleccionado(s).
        /// </summary>
        public static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona persona autorizada.
        /// </summary>
        public static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione tipo.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Define el período.
        /// </summary>
        public static string SetDates {
            get {
                return ResourceManager.GetString("SetDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        public static string TutorDashboard {
            get {
                return ResourceManager.GetString("TutorDashboard", resourceCulture);
            }
        }

        public static string MyChildren {
            get {
                return ResourceManager.GetString("MyChildren", resourceCulture);
            }
        }

        public static string AuthorizedPersonsMenu {
            get {
                return ResourceManager.GetString("AuthorizedPersonsMenu", resourceCulture);
            }
        }

        public static string AuthorizationCalendar {
            get {
                return ResourceManager.GetString("AuthorizationCalendar", resourceCulture);
            }
        }

        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        public static string TeacherDashboard {
            get {
                return ResourceManager.GetString("TeacherDashboard", resourceCulture);
            }
        }

        public static string DailyPickupList {
            get {
                return ResourceManager.GetString("DailyPickupList", resourceCulture);
            }
        }

        public static string LoginAsTeacher {
            get {
                return ResourceManager.GetString("LoginAsTeacher", resourceCulture);
            }
        }

        public static string LoginAsTutor {
            get {
                return ResourceManager.GetString("LoginAsTutor", resourceCulture);
            }
        }

        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }

        public static string PendingPickups {
            get {
                return ResourceManager.GetString("PendingPickups", resourceCulture);
            }
        }

        public static string NoPendingPickups {
            get {
                return ResourceManager.GetString("NoPendingPickups", resourceCulture);
            }
        }

        public static string PickedUp {
            get {
                return ResourceManager.GetString("PickedUp", resourceCulture);
            }
        }

        public static string NoChildrenPickedUpYet {
            get {
                return ResourceManager.GetString("NoChildrenPickedUpYet", resourceCulture);
            }
        }

        public static string EnterCanPrompt {
            get {
                return ResourceManager.GetString("EnterCanPrompt", resourceCulture);
            }
        }

        public static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }

        public static string BringDnieClose {
            get {
                return ResourceManager.GetString("BringDnieClose", resourceCulture);
            }
        }

        public static string UsernameOrEmail {
            get {
                return ResourceManager.GetString("UsernameOrEmail", resourceCulture);
            }
        }

        public static string DashboardGreeting {
            get {
                return ResourceManager.GetString("DashboardGreeting", resourceCulture);
            }
        }

        public static string PendingApprovals {
            get {
                return ResourceManager.GetString("PendingApprovals", resourceCulture);
            }
        }

        public static string NoPendingApprovals {
            get {
                return ResourceManager.GetString("NoPendingApprovals", resourceCulture);
            }
        }

        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }

        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }

        public static string RejectedRegistration {
            get {
                return ResourceManager.GetString("RejectedRegistration", resourceCulture);
            }
        }

        public static string RejectChild {
            get {
                return ResourceManager.GetString("RejectChild", resourceCulture);
            }
        }

        public static string EnterRejectionReason {
            get {
                return ResourceManager.GetString("EnterRejectionReason", resourceCulture);
            }
        }

        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }

        public static string ReasonPlaceholder {
            get {
                return ResourceManager.GetString("ReasonPlaceholder", resourceCulture);
            }
        }

        public static string NfcNotSupported {
            get {
                return ResourceManager.GetString("NfcNotSupported", resourceCulture);
            }
        }

        public static string NfcDisabledWarning {
            get {
                return ResourceManager.GetString("NfcDisabledWarning", resourceCulture);
            }
        }

        public static string ChildNotSpecified {
            get {
                return ResourceManager.GetString("ChildNotSpecified", resourceCulture);
            }
        }

        public static string CanMustBe6Digits {
            get {
                return ResourceManager.GetString("CanMustBe6Digits", resourceCulture);
            }
        }

        public static string InvalidPickupContext {
            get {
                return ResourceManager.GetString("InvalidPickupContext", resourceCulture);
            }
        }

        public static string TimeoutExpired {
            get {
                return ResourceManager.GetString("TimeoutExpired", resourceCulture);
            }
        }

        public static string DniNotDetectedTimeout {
            get {
                return ResourceManager.GetString("DniNotDetectedTimeout", resourceCulture);
            }
        }

        public static string VerificationError {
            get {
                return ResourceManager.GetString("VerificationError", resourceCulture);
            }
        }

        public static string NoActivePickupContext {
            get {
                return ResourceManager.GetString("NoActivePickupContext", resourceCulture);
            }
        }

        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }

        public static string PickupAuthorized {
            get {
                return ResourceManager.GetString("PickupAuthorized", resourceCulture);
            }
        }

        public static string PersonCanPickupChild {
            get {
                return ResourceManager.GetString("PersonCanPickupChild", resourceCulture);
            }
        }

        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }

        public static string CouldNotLoadPickups {
            get {
                return ResourceManager.GetString("CouldNotLoadPickups", resourceCulture);
            }
        }

        public static string ChildAlreadyPickedUp {
            get {
                return ResourceManager.GetString("ChildAlreadyPickedUp", resourceCulture);
            }
        }

        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        public static string LanguageChangedRestart {
            get {
                return ResourceManager.GetString("LanguageChangedRestart", resourceCulture);
            }
        }

        public static string ErrorLoadingAuthorizedPersons {
            get {
                return ResourceManager.GetString("ErrorLoadingAuthorizedPersons", resourceCulture);
            }
        }

        public static string ErrorLoadingChildren {
            get {
                return ResourceManager.GetString("ErrorLoadingChildren", resourceCulture);
            }
        }
    }
}
